version: '3.8'
services:
  app:
    container_name: Bookare
    build: ./
    ports:
      - "8899:8899"
    links:
     - dbpostgresql
    depends_on:
      - dbpostgresql
    env_file:
      - .env
  dbpostgresql:
    image: postgres
    container_name: db-bookare
    ports:
      - "5433:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: bookare-prometheus
    restart: unless-stopped
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus:/etc/prometheus_config/prometheus.yaml
      - ./prometheus_data:/prometheus_data/data
      - ./prometheus_data:/prometheus_data/data/queries.active

    command:
        - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    #network_mode: host
    container_name: bookare-grafana
    restart: unless-stopped
    user: "1001"
    ports:
      - "3003:3000"
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

volumes:
  grafana-storage: